[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "TheEyeOfSauron"
version = "2.1.0"
description = "Telegram Orchestra Poll Parser"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "Telethon==1.42.0",
  "requests==2.32.5",
  "rsa==4.9.1",
  "tzdata==2025.3",
]

[project.scripts]
eye-of-sauron = "eye.__main__:run"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]